--CREATE DATABASE jh_prueba


use jh_prueba


CREATE TABLE Genres(
	genreId INTEGER NOT NULL IDENTITY PRIMARY KEY,
	code VARCHAR(10) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	createdAt DATETIME NOT NULL,
);

GO

CREATE TABLE Authors(
	authorId INTEGER NOT NULL IDENTITY PRIMARY KEY,
	author VARCHAR(250) NOT NULL,
	createdAt DATETIME NOT NULL,
);

GO

CREATE TABLE Books(
	bookId INTEGER NOT NULL IDENTITY PRIMARY KEY,
	title VARCHAR(250) NOT NULL,
	isbn VARCHAR(50) NOT NULL,
	genreId INTEGER NOT NULL,
	authorId INTEGER NOT NULL,
	publicationDate DATETIME NOT NULL,
	borrowed BIT NOT NULL,
	createdAt DATETIME NOT NULL,
	FOREIGN KEY (genreId) REFERENCES Genres(genreId),
    FOREIGN KEY (authorId) REFERENCES Authors(authorId)
);

GO

CREATE TABLE Members(
	memberId INTEGER NOT NULL IDENTITY PRIMARY KEY,
	memberName VARCHAR(100) NOT NULL,
	cellNumber VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	createdAt DATETIME NOT NULL,
);

GO

CREATE TABLE Loans(
	loanId INTEGER NOT NULL IDENTITY PRIMARY KEY,
	memberId INTEGER NOT NULL,
	bookId INTEGER NOT NULL,
	loanDate DATE NOT NULL, 
	dueDate DATE NOT NULL, 
	returnDate DATE NOT NULL,
	createdAt DATETIME NOT NULL,
	FOREIGN KEY (memberId) REFERENCES Members(memberId),
    FOREIGN KEY (bookId) REFERENCES Books(bookId)
);